/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/common/components/AppLogo.vue')['default']
    BaseButton: typeof import('./src/common/components/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/common/components/BaseCheckbox.vue')['default']
    BaseCommandPalette: typeof import('./src/common/components/BaseCommandPalette.vue')['default']
    BaseCommandPaletteItem: typeof import('./src/common/components/BaseCommandPaletteItem.vue')['default']
    BaseEmptyState: typeof import('./src/common/components/BaseEmptyState.vue')['default']
    BaseHeading: typeof import('./src/common/components/BaseHeading.vue')['default']
    BaseInput: typeof import('./src/common/components/BaseInput.vue')['default']
    BaseKbd: typeof import('./src/common/components/BaseKbd.vue')['default']
    BaseKbdGroup: typeof import('./src/common/components/BaseKbdGroup.vue')['default']
    BaseLabel: typeof import('./src/common/components/BaseLabel.vue')['default']
    BaseLink: typeof import('./src/common/components/BaseLink.vue')['default']
    BaseMenu: typeof import('./src/common/components/BaseMenu.vue')['default']
    BaseMenuButton: typeof import('./src/common/components/BaseMenuButton.vue')['default']
    BaseMenuDivider: typeof import('./src/common/components/BaseMenuDivider.vue')['default']
    BaseModal: typeof import('./src/common/components/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/common/components/BaseSelect.vue')['default']
    BaseSpinner: typeof import('./src/common/components/BaseSpinner.vue')['default']
    BaseTabs: typeof import('./src/common/components/BaseTabs.vue')['default']
    BaseTitle: typeof import('./src/common/components/BaseTitle.vue')['default']
    BaseToast: typeof import('./src/common/components/BaseToast.vue')['default']
    CenteredAuthModal: typeof import('./src/common/components/CenteredAuthModal.vue')['default']
    CookieBanner: typeof import('./src/common/components/CookieBanner.vue')['default']
    InfoModal: typeof import('./src/common/components/InfoModal.vue')['default']
    LocaleDropdown: typeof import('./src/common/components/LocaleDropdown.vue')['default']
    LocaleMenuDropdown: typeof import('./src/common/components/LocaleMenuDropdown.vue')['default']
    MenuDropdown: typeof import('./src/common/components/MenuDropdown.vue')['default']
    NotificationDot: typeof import('./src/common/components/NotificationDot.vue')['default']
    PageHeader: typeof import('./src/common/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tagline: typeof import('./src/common/components/Tagline.vue')['default']
    ThemeDropdown: typeof import('./src/common/components/ThemeDropdown.vue')['default']
    ThemeMenuDropdown: typeof import('./src/common/components/ThemeMenuDropdown.vue')['default']
    VideoPlayer: typeof import('./src/common/components/VideoPlayer.vue')['default']
  }
}
