// Regenerates ui/icons/Lucide.kt from the web app's @lucide/vue icons, so both clients draw
// the same glyphs. Keeps every icon already in the file and adds the ones named on the command
// line (their @lucide/vue export names).
//
//   node scripts/generate-lucide.js [IconName ...]
//
// Needs the web app's dependencies installed (`app/node_modules`).
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dir = path.resolve(root, '../app/node_modules/@lucide/vue/dist/esm');
const out = path.join(root, 'app/src/main/kotlin/app/schuldashboard/ui/icons/Lucide.kt');

const existing = fs.existsSync(out)
  ? [...fs.readFileSync(out, 'utf8').matchAll(/val (\w+) = LucideIcon\(/g)].map((m) => m[1])
  : [];
const names = [...new Set([...existing, ...process.argv.slice(2)])].sort();
const index = fs.readFileSync(path.join(dir, 'lucide-vue.js'), 'utf8');

function fileFor(name) {
  const match = index.match(new RegExp(`default as ${name}[ ,][^;]*from '\\./icons/([a-z0-9-]+)\\.js'`));
  if (!match) throw new Error(`No Lucide icon exported as ${name}`);
  return match[1];
}

function nodes(file) {
  const source = fs.readFileSync(path.join(dir, 'icons', `${file}.js`), 'utf8');
  const literal = source.match(/const __iconNode = (\[[\s\S]*?\]);\nconst /)[1];
  return Function(`return ${literal}`)();
}

const n = Number;

/** Every element as one SVG path, since Compose's vector builder only takes paths. */
function toPath([tag, a]) {
  switch (tag) {
    case 'path':
      return a.d;
    case 'line':
      return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
    case 'polyline':
    case 'polygon': {
      const p = a.points.trim().split(/[\s,]+/);
      let d = `M${p[0]} ${p[1]}`;
      for (let i = 2; i < p.length; i += 2) d += `L${p[i]} ${p[i + 1]}`;
      return tag === 'polygon' ? `${d}Z` : d;
    }
    case 'circle': {
      const [cx, cy, r] = [n(a.cx), n(a.cy), n(a.r)];
      return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0`;
    }
    case 'ellipse': {
      const [cx, cy, rx, ry] = [n(a.cx), n(a.cy), n(a.rx), n(a.ry)];
      return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`;
    }
    case 'rect': {
      const [x, y, w, h] = [n(a.x || 0), n(a.y || 0), n(a.width), n(a.height)];
      const rx = a.rx != null ? n(a.rx) : a.ry != null ? n(a.ry) : 0;
      const ry = a.ry != null ? n(a.ry) : rx;
      if (!rx) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return (
        `M${x + rx} ${y}h${w - 2 * rx}a${rx} ${ry} 0 0 1 ${rx} ${ry}v${h - 2 * ry}` +
        `a${rx} ${ry} 0 0 1 ${-rx} ${ry}h${-(w - 2 * rx)}a${rx} ${ry} 0 0 1 ${-rx} ${-ry}` +
        `v${-(h - 2 * ry)}a${rx} ${ry} 0 0 1 ${rx} ${-ry}Z`
      );
    }
    default:
      throw new Error(`Unsupported SVG element ${tag}`);
  }
}

const body = names
  .map((name) => {
    const paths = nodes(fileFor(name)).map(toPath).map((d) => `        ${JSON.stringify(d)},`);
    return `    val ${name} = LucideIcon(\n${paths.join('\n')}\n    )\n`;
  })
  .join('');

fs.writeFileSync(
  out,
  `package app.schuldashboard.ui.icons

// Generated by scripts/generate-lucide.js from the web app's @lucide/vue icons (ISC license).
object Lucide {
${body}}
`,
);
console.log(`${names.length} icons written to ${path.relative(root, out)}`);
