name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 91.98.235.207
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /root/codes/main-server/234u88
            git reset --hard origin/main
            git pull
            cd backup2hwserver
            npm ci
            pm2 reload all
            sudo caddy reload --config /etc/caddy/Caddyfile
